export const CATEGORIES = [
	{
		id: 1,
		name: 'MO?s Algorithm (Query square root decomposition)',
		problems: [
			{
				ID: '2',
				'Problem Name': "Mr. Kitayuta's Colorful Graph",
				'Online Judge': 'Codeforces',
				'Difficulty Level': '2',
				link: 'http://codeforces.com/problemset/problem/506/D',
			},
			{
				ID: '5',
				'Problem Name': 'Little Elephant and Array',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '3',
				link: 'http://codeforces.com/problemset/problem/220/B',
			},
			{
				ID: '6',
				'Problem Name': 'Powerful array',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '3',
				link: 'http://codeforces.com/problemset/problem/86/D',
			},
			{
				ID: '8',
				'Problem Name': 'XOR and Favorite Number',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '4',
				link: 'http://codeforces.com/problemset/problem/617/E',
			},
			{
				ID: '9',
				'Problem Name': 'Xenia and Tree',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '4',
				link: 'http://codeforces.com/problemset/problem/342/E',
			},
			{
				ID: '10',
				'Problem Name': 'Little Artem and Time Machine',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '5',
				link: 'http://codeforces.com/problemset/problem/641/E',
			},
			{
				ID: '11',
				'Problem Name': 'Tree and Queries',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '5',
				link: 'http://codeforces.com/problemset/problem/375/D',
			},
			{
				ID: '12',
				'Problem Name': 'DZY Loves Colors',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '6',
				link: 'http://codeforces.com/problemset/problem/444/C',
			},
			{
				ID: '13',
				'Problem Name': 'Holidays',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '6',
				link: 'http://codeforces.com/problemset/problem/44/C',
			},
			{
				ID: '15',
				'Problem Name': 'Holes',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '6',
				link: 'http://codeforces.com/problemset/problem/13/E',
			},
			{
				ID: '16',
				'Problem Name': 'Serega and Fun',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '6',
				link: 'http://codeforces.com/problemset/problem/455/D',
			},
			{
				ID: '18',
				'Problem Name': 'DZY Loves Fibonacci Numbers',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '6',
				link: 'http://codeforces.com/problemset/problem/446/C',
			},
			{
				ID: '19',
				'Problem Name': 'Subset Sums',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/348/C',
			},
			{
				ID: '20',
				'Problem Name': 'Conveyor Belts',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/487/D',
			},
			{
				ID: '21',
				'Problem Name': 'Ann and Books',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/877/F',
			},
			{
				ID: '22',
				'Problem Name': 'Instant Messanger',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/398/D',
			},
			{
				ID: '23',
				'Problem Name': 'Jeff and Removing Periods',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/351/D',
			},
			{
				ID: '24',
				'Problem Name': 'Destiny',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/840/D',
			},
		],
	},
	{
		id: 2,
		name: 'Articulation Point',
		problems: [
			{
				ID: '8',
				'Problem Name': 'Cutting Figure',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '5',
				link: 'http://codeforces.com/problemset/problem/193/A',
			},
		],
	},
	{
		id: 3,
		name: 'Strongly Connected Components',
		problems: [
			{
				ID: '9',
				'Problem Name': 'Checkposts',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '2',
				link: 'http://codeforces.com/problemset/problem/427/C',
			},
			{
				ID: '14',
				'Problem Name': 'Ralph and Mushrooms',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/894/E',
			},
			{
				ID: '15',
				'Problem Name': 'Scheme',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/22/E',
			},
		],
	},
	{
		id: 4,
		name: 'FFT',
		problems: [
			{
				ID: '9',
				'Problem Name': 'Fuzzy Search',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/528/D',
			},
			{
				ID: '10',
				'Problem Name': 'Binary Table',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/662/C',
			},
			{
				ID: '11',
				'Problem Name': 'DZY Loves FFT',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/444/B',
			},
			{
				ID: '12',
				'Problem Name': 'Thief in a Shop',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/632/E',
			},
			{
				ID: '13',
				'Problem Name': 'The Child and Binary Tree',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/438/E',
			},
			{
				ID: '14',
				'Problem Name': 'Painting Square',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/300/D',
			},
			{
				ID: '15',
				'Problem Name': "Ladies' Shop",
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/286/E',
			},
			{
				ID: '17',
				'Problem Name': 'Dasha and cyclic table',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '9',
				link: 'http://codeforces.com/problemset/problem/754/E',
			},
			{
				ID: '19',
				'Problem Name': 'Design Tutorial: Increase the Constraints',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '9',
				link: 'http://codeforces.com/problemset/problem/472/G',
			},
			{
				ID: '20',
				'Problem Name': 'Transforming Sequence',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '9',
				link: 'http://codeforces.com/problemset/problem/623/E',
			},
			{
				ID: '21',
				'Problem Name': 'Nephren Runs a Cinema',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '10',
				link: 'http://codeforces.com/problemset/problem/896/D',
			},
			{
				ID: '22',
				'Problem Name': 'Kyoya and Train',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '10',
				link: 'http://codeforces.com/problemset/problem/553/E',
			},
			{
				ID: '23',
				'Problem Name': 'Days of Floral Colours',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '10',
				link: 'http://codeforces.com/problemset/problem/848/E',
			},
		],
	},
	{
		id: 5,
		name: 'graphs',
		problems: [
			{
				ID: '1',
				'Problem Name': 'Ice Skating',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '1',
				link: 'http://codeforces.com/problemset/problem/217/A',
			},
			{
				ID: '2',
				'Problem Name': 'Party',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '1',
				link: 'http://codeforces.com/problemset/problem/115/A',
			},
			{
				ID: '3',
				'Problem Name': 'Dijkstra?',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '1',
				link: 'http://codeforces.com/problemset/problem/20/C',
			},
			{
				ID: '14',
				'Problem Name': 'Two Buttons',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '1',
				link: 'http://codeforces.com/problemset/problem/520/B',
			},
			{
				ID: '15',
				'Problem Name': 'New Year Transportation',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '1',
				link: 'http://codeforces.com/problemset/problem/500/A',
			},
			{
				ID: '16',
				'Problem Name': 'Road Construction',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '1',
				link: 'http://codeforces.com/problemset/problem/330/B',
			},
			{
				ID: '17',
				'Problem Name': 'Young Physicist',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '1',
				link: 'http://codeforces.com/problemset/problem/69/A',
			},
			{
				ID: '19',
				'Problem Name': 'NP-Hard Problem',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '1',
				link: 'http://codeforces.com/problemset/problem/687/A',
			},
			{
				ID: '20',
				'Problem Name': 'Bakery',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '1',
				link: 'http://codeforces.com/problemset/problem/707/B',
			},
			{
				ID: '28',
				'Problem Name': 'Bear and Forgotten Tree 3',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '2',
				link: 'http://codeforces.com/problemset/problem/639/B',
			},
			{
				ID: '29',
				'Problem Name': 'The Two Routes',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '2',
				link: 'http://codeforces.com/problemset/problem/601/A',
			},
			{
				ID: '30',
				'Problem Name': 'Bear and Three Musketeers',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '2',
				link: 'http://codeforces.com/problemset/problem/574/B',
			},
			{
				ID: '31',
				'Problem Name': 'Reposts',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '2',
				link: 'http://codeforces.com/problemset/problem/522/A',
			},
			{
				ID: '32',
				'Problem Name': 'Fox And Names',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '2',
				link: 'http://codeforces.com/problemset/problem/510/C',
			},
			{
				ID: '33',
				'Problem Name': "Mr. Kitayuta's Colorful Graph",
				'Online Judge': 'Codeforces',
				'Difficulty Level': '2',
				link: 'http://codeforces.com/problemset/problem/506/D',
			},
			{
				ID: '34',
				'Problem Name': 'New Year Permutation',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '2',
				link: 'http://codeforces.com/problemset/problem/500/B',
			},
			{
				ID: '35',
				'Problem Name': 'Strongly Connected City',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '2',
				link: 'http://codeforces.com/problemset/problem/475/B',
			},
			{
				ID: '36',
				'Problem Name': 'The Child and Toy',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '2',
				link: 'http://codeforces.com/problemset/problem/437/C',
			},
			{
				ID: '37',
				'Problem Name': 'Checkposts',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '2',
				link: 'http://codeforces.com/problemset/problem/427/C',
			},
			{
				ID: '39',
				'Problem Name': 'Colorful Graph',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '3',
				link: 'http://codeforces.com/problemset/problem/246/D',
			},
			{
				ID: '40',
				'Problem Name': 'Students and Shoelaces',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '3',
				link: 'http://codeforces.com/problemset/problem/129/B',
			},
			{
				ID: '41',
				'Problem Name': 'Cthulhu',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '3',
				link: 'http://codeforces.com/problemset/problem/103/B',
			},
			{
				ID: '45',
				'Problem Name': 'New Reform',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '3',
				link: 'http://codeforces.com/problemset/problem/659/E',
			},
			{
				ID: '46',
				'Problem Name': 'Graph and String',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '3',
				link: 'http://codeforces.com/problemset/problem/623/A',
			},
			{
				ID: '47',
				'Problem Name': 'Longtail Hedgehog',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '3',
				link: 'http://codeforces.com/problemset/problem/615/B',
			},
			{
				ID: '48',
				'Problem Name': 'Unbearable Controversy of Being',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '3',
				link: 'http://codeforces.com/problemset/problem/489/D',
			},
			{
				ID: '49',
				'Problem Name': 'Gargari and Permutations',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '3',
				link: 'http://codeforces.com/problemset/problem/463/D',
			},
			{
				ID: '50',
				'Problem Name': 'Football',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '3',
				link: 'http://codeforces.com/problemset/problem/417/C',
			},
			{
				ID: '51',
				'Problem Name': 'Valera and Elections',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '3',
				link: 'http://codeforces.com/problemset/problem/369/C',
			},
			{
				ID: '52',
				'Problem Name': 'Ping-Pong (Easy Version)',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '3',
				link: 'http://codeforces.com/problemset/problem/320/B',
			},
			{
				ID: '53',
				'Problem Name': 'Greg and Graph',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '3',
				link: 'http://codeforces.com/problemset/problem/295/B',
			},
			{
				ID: '54',
				'Problem Name': 'Network Topology',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '3',
				link: 'http://codeforces.com/problemset/problem/292/B',
			},
			{
				ID: '55',
				'Problem Name': 'Searching for Graph',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '3',
				link: 'http://codeforces.com/problemset/problem/402/C',
			},
			{
				ID: '56',
				'Problem Name': 'Misha and Forest',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '3',
				link: 'http://codeforces.com/problemset/problem/501/C',
			},
			{
				ID: '59',
				'Problem Name': 'Hongcow Builds A Nation',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '3',
				link: 'http://codeforces.com/problemset/problem/744/A',
			},
			{
				ID: '60',
				'Problem Name': 'Journey',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '3',
				link: 'http://codeforces.com/problemset/problem/721/C',
			},
			{
				ID: '62',
				'Problem Name': "King's Path",
				'Online Judge': 'Codeforces',
				'Difficulty Level': '4',
				link: 'http://codeforces.com/problemset/problem/242/C',
			},
			{
				ID: '63',
				'Problem Name': 'Subway',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '4',
				link: 'http://codeforces.com/problemset/problem/131/D',
			},
			{
				ID: '64',
				'Problem Name': 'Dorm Water Supply',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '4',
				link: 'http://codeforces.com/problemset/problem/107/A',
			},
			{
				ID: '65',
				'Problem Name': 'Eternal Victory',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '4',
				link: 'http://codeforces.com/problemset/problem/61/D',
			},
			{
				ID: '66',
				'Problem Name': 'Road Map',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '4',
				link: 'http://codeforces.com/problemset/problem/34/D',
			},
			{
				ID: '67',
				'Problem Name': 'Roads not only in Berland',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '4',
				link: 'http://codeforces.com/problemset/problem/25/D',
			},
			{
				ID: '68',
				'Problem Name': 'Roads in Berland',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '4',
				link: 'http://codeforces.com/problemset/problem/25/C',
			},
			{
				ID: '69',
				'Problem Name': 'Ring road',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '4',
				link: 'http://codeforces.com/problemset/problem/24/A',
			},
			{
				ID: '77',
				'Problem Name': 'Lazy Student',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '4',
				link: 'http://codeforces.com/problemset/problem/605/B',
			},
			{
				ID: '78',
				'Problem Name': 'Regular Bridge',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '4',
				link: 'http://codeforces.com/problemset/problem/550/D',
			},
			{
				ID: '79',
				'Problem Name': 'Paths and Trees',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '4',
				link: 'http://codeforces.com/problemset/problem/545/E',
			},
			{
				ID: '80',
				'Problem Name': 'Destroying Roads',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '4',
				link: 'http://codeforces.com/problemset/problem/543/B',
			},
			{
				ID: '81',
				'Problem Name': 'New Year Santa Network',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '4',
				link: 'http://codeforces.com/problemset/problem/500/D',
			},
			{
				ID: '82',
				'Problem Name': 'Jzzhu and Cities',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '4',
				link: 'http://codeforces.com/problemset/problem/449/B',
			},
			{
				ID: '83',
				'Problem Name': 'Restore Graph',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '4',
				link: 'http://codeforces.com/problemset/problem/404/C',
			},
			{
				ID: '84',
				'Problem Name': 'Cow Program',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '4',
				link: 'http://codeforces.com/problemset/problem/283/B',
			},
			{
				ID: '86',
				'Problem Name': 'Connecting Universities',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '4',
				link: 'http://codeforces.com/problemset/problem/700/B',
			},
			{
				ID: '87',
				'Problem Name': 'Alyona and a tree',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '4',
				link: 'http://codeforces.com/problemset/problem/739/B',
			},
			{
				ID: '88',
				'Problem Name': 'Resort',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '4',
				link: 'http://codeforces.com/problemset/problem/350/B',
			},
			{
				ID: '89',
				'Problem Name': 'Directed Roads',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '4',
				link: 'http://codeforces.com/problemset/problem/711/D',
			},
			{
				ID: '90',
				'Problem Name': 'Garland',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '4',
				link: 'http://codeforces.com/problemset/problem/767/C',
			},
			{
				ID: '92',
				'Problem Name': 'Union of Doubly Linked Lists',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '4',
				link: 'http://codeforces.com/problemset/problem/847/A',
			},
			{
				ID: '94',
				'Problem Name': 'Reachability from the Capital',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '4',
				link: 'http://codeforces.com/problemset/problem/999/E',
			},
			{
				ID: '95',
				'Problem Name': 'Cycles',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '5',
				link: 'http://codeforces.com/problemset/problem/232/A',
			},
			{
				ID: '96',
				'Problem Name': 'Missile Silos',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '5',
				link: 'http://codeforces.com/problemset/problem/144/D',
			},
			{
				ID: '97',
				'Problem Name': 'Help General',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '5',
				link: 'http://codeforces.com/problemset/problem/142/B',
			},
			{
				ID: '98',
				'Problem Name': 'Cycle',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '5',
				link: 'http://codeforces.com/problemset/problem/117/C',
			},
			{
				ID: '99',
				'Problem Name': 'Volleyball',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '5',
				link: 'http://codeforces.com/problemset/problem/95/C',
			},
			{
				ID: '100',
				'Problem Name': 'Mail Stamps',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '5',
				link: 'http://codeforces.com/problemset/problem/29/C',
			},
			{
				ID: '101',
				'Problem Name': 'pSort',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '5',
				link: 'http://codeforces.com/problemset/problem/28/B',
			},
			{
				ID: '102',
				'Problem Name': 'Two Paths',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '5',
				link: 'http://codeforces.com/problemset/problem/14/D',
			},
			{
				ID: '103',
				'Problem Name': 'A Simple Task',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '5',
				link: 'http://codeforces.com/problemset/problem/11/D',
			},
			{
				ID: '104',
				'Problem Name': 'Clique in the Divisibility Graph',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '5',
				link: 'http://codeforces.com/problemset/problem/566/F',
			},
			{
				ID: '106',
				'Problem Name': 'Robot Rapping Results Report',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '5',
				link: 'http://codeforces.com/problemset/problem/645/D',
			},
			{
				ID: '107',
				'Problem Name': 'Minimum spanning tree for each edge',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '5',
				link: 'http://codeforces.com/problemset/problem/609/E',
			},
			{
				ID: '108',
				'Problem Name': 'Three States',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '5',
				link: 'http://codeforces.com/problemset/problem/590/C',
			},
			{
				ID: '109',
				'Problem Name': 'Vitaly and Cycle',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '5',
				link: 'http://codeforces.com/problemset/problem/557/D',
			},
			{
				ID: '110',
				'Problem Name': 'Breaking Good',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '5',
				link: 'http://codeforces.com/problemset/problem/507/E',
			},
			{
				ID: '111',
				'Problem Name': 'Dungeons and Candies',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '5',
				link: 'http://codeforces.com/problemset/problem/436/C',
			},
			{
				ID: '112',
				'Problem Name': 'Dima and Bacteria',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '5',
				link: 'http://codeforces.com/problemset/problem/400/D',
			},
			{
				ID: '113',
				'Problem Name': 'Fox and Minimal path',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '5',
				link: 'http://codeforces.com/problemset/problem/388/B',
			},
			{
				ID: '114',
				'Problem Name': 'Inna and Dima',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '5',
				link: 'http://codeforces.com/problemset/problem/374/C',
			},
			{
				ID: '115',
				'Problem Name': 'Block Tower',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '5',
				link: 'http://codeforces.com/problemset/problem/327/D',
			},
			{
				ID: '116',
				'Problem Name': 'Yaroslav and Time',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '5',
				link: 'http://codeforces.com/problemset/problem/301/B',
			},
			{
				ID: '117',
				'Problem Name': 'Cycle in Graph',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '5',
				link: 'http://codeforces.com/problemset/problem/263/D',
			},
			{
				ID: '118',
				'Problem Name': 'Obsession with Robots',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '5',
				link: 'http://codeforces.com/problemset/problem/8/B',
			},
			{
				ID: '119',
				'Problem Name': 'Complete The Graph',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '5',
				link: 'http://codeforces.com/problemset/problem/715/B',
			},
			{
				ID: '120',
				'Problem Name': 'Weird journey',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '5',
				link: 'http://codeforces.com/problemset/problem/788/B',
			},
			{
				ID: '121',
				'Problem Name': 'Mahmoud and a Dictionary',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '5',
				link: 'http://codeforces.com/problemset/problem/766/D',
			},
			{
				ID: '123',
				'Problem Name': 'Hydra',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '6',
				link: 'http://codeforces.com/problemset/problem/243/B',
			},
			{
				ID: '124',
				'Problem Name': 'Dispute',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '6',
				link: 'http://codeforces.com/problemset/problem/242/D',
			},
			{
				ID: '125',
				'Problem Name': 'Triangles',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '6',
				link: 'http://codeforces.com/problemset/problem/229/C',
			},
			{
				ID: '126',
				'Problem Name': 'The Road to Berland is Paved With Good Intentions',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '6',
				link: 'http://codeforces.com/problemset/problem/228/E',
			},
			{
				ID: '127',
				'Problem Name': 'Police Station',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '6',
				link: 'http://codeforces.com/problemset/problem/208/C',
			},
			{
				ID: '128',
				'Problem Name': 'Party',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '6',
				link: 'http://codeforces.com/problemset/problem/177/C2',
			},
			{
				ID: '129',
				'Problem Name': 'Party',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '6',
				link: 'http://codeforces.com/problemset/problem/177/C1',
			},
			{
				ID: '130',
				'Problem Name': 'Double Profiles',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '6',
				link: 'http://codeforces.com/problemset/problem/154/C',
			},
			{
				ID: '131',
				'Problem Name': 'Bertown roads',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '6',
				link: 'http://codeforces.com/problemset/problem/118/E',
			},
			{
				ID: '132',
				'Problem Name': '3-cycles',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '6',
				link: 'http://codeforces.com/problemset/problem/41/E',
			},
			{
				ID: '133',
				'Problem Name': 'Ring Road 2',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '6',
				link: 'http://codeforces.com/problemset/problem/27/D',
			},
			{
				ID: '134',
				'Problem Name': 'System Administrator',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '6',
				link: 'http://codeforces.com/problemset/problem/22/C',
			},
			{
				ID: '138',
				'Problem Name': 'Information Graph',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '6',
				link: 'http://codeforces.com/problemset/problem/466/E',
			},
			{
				ID: '139',
				'Problem Name': 'Polycarp and Hay',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '6',
				link: 'http://codeforces.com/problemset/problem/659/F',
			},
			{
				ID: '140',
				'Problem Name': 'Table Compression',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '6',
				link: 'http://codeforces.com/problemset/problem/650/C',
			},
			{
				ID: '141',
				'Problem Name': 'Love Triangles',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '6',
				link: 'http://codeforces.com/problemset/problem/553/C',
			},
			{
				ID: '142',
				'Problem Name': 'Work Group',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '6',
				link: 'http://codeforces.com/problemset/problem/533/B',
			},
			{
				ID: '143',
				'Problem Name': 'Tanya and Password',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '6',
				link: 'http://codeforces.com/problemset/problem/508/D',
			},
			{
				ID: '144',
				'Problem Name': 'Fedor and Essay',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '6',
				link: 'http://codeforces.com/problemset/problem/467/D',
			},
			{
				ID: '145',
				'Problem Name': 'Strictly Positive Matrix',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '6',
				link: 'http://codeforces.com/problemset/problem/402/E',
			},
			{
				ID: '146',
				'Problem Name': 'Sereja and the Arrangement of Numbers',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '6',
				link: 'http://codeforces.com/problemset/problem/367/C',
			},
			{
				ID: '147',
				'Problem Name': 'Greg and Friends',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '6',
				link: 'http://codeforces.com/problemset/problem/295/C',
			},
			{
				ID: '148',
				'Problem Name': 'Flawed Flow',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '6',
				link: 'http://codeforces.com/problemset/problem/269/C',
			},
			{
				ID: '149',
				'Problem Name': 'Partial Teacher',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '6',
				link: 'http://codeforces.com/problemset/problem/67/A',
			},
			{
				ID: '150',
				'Problem Name': 'Party',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '6',
				link: 'http://codeforces.com/problemset/problem/23/B',
			},
			{
				ID: '151',
				'Problem Name': 'World Tour',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '6',
				link: 'http://codeforces.com/problemset/problem/666/B',
			},
			{
				ID: '152',
				'Problem Name': "Mr. Kitayuta's Technology",
				'Online Judge': 'Codeforces',
				'Difficulty Level': '6',
				link: 'http://codeforces.com/problemset/problem/505/D',
			},
			{
				ID: '153',
				'Problem Name': 'Vanya and Treasure',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '6',
				link: 'http://codeforces.com/problemset/problem/677/D',
			},
			{
				ID: '155',
				'Problem Name': 'Leha and another game about graph',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '6',
				link: 'http://codeforces.com/problemset/problem/840/B',
			},
			{
				ID: '156',
				'Problem Name': 'Legacy',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '6',
				link: 'http://codeforces.com/problemset/problem/786/B',
			},
			{
				ID: '157',
				'Problem Name': 'The Great Mixing',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '6',
				link: 'http://codeforces.com/problemset/problem/788/C',
			},
			{
				ID: '158',
				'Problem Name': 'Vladik and Favorite Game',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '6',
				link: 'http://codeforces.com/problemset/problem/811/D',
			},
			{
				ID: '163',
				'Problem Name': 'Build String',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/237/E',
			},
			{
				ID: '164',
				'Problem Name': 'Cactus',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/231/E',
			},
			{
				ID: '165',
				'Problem Name': 'Snake',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/225/D',
			},
			{
				ID: '166',
				'Problem Name': 'Counter Attack',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/190/E',
			},
			{
				ID: '167',
				'Problem Name': 'Variable, or There and Back Again',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/164/A',
			},
			{
				ID: '168',
				'Problem Name': 'Edges in MST',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/160/D',
			},
			{
				ID: '169',
				'Problem Name': 'Lucky Country',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/95/E',
			},
			{
				ID: '170',
				'Problem Name': 'Ski Base',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/91/C',
			},
			{
				ID: '171',
				'Problem Name': 'Gift',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/76/A',
			},
			{
				ID: '172',
				'Problem Name': 'Chessboard Billiard',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/74/C',
			},
			{
				ID: '173',
				'Problem Name': 'Shortest Path',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/59/E',
			},
			{
				ID: '174',
				'Problem Name': 'Knights',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/33/D',
			},
			{
				ID: '175',
				'Problem Name': 'Graph Reconstruction',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/329/C',
			},
			{
				ID: '177',
				'Problem Name': 'Bear and Forgotten Tree 2',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/653/E',
			},
			{
				ID: '178',
				'Problem Name': 'Pursuit For Artifacts',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/652/E',
			},
			{
				ID: '179',
				'Problem Name': 'Three-dimensional Turtle Super Computer ',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/638/D',
			},
			{
				ID: '180',
				'Problem Name': 'Square Root of Permutation',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/612/E',
			},
			{
				ID: '181',
				'Problem Name': 'President and Roads',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/567/E',
			},
			{
				ID: '182',
				'Problem Name': 'Case of Computer Network',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/555/E',
			},
			{
				ID: '183',
				'Problem Name': 'Nudist Beach',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/553/D',
			},
			{
				ID: '184',
				'Problem Name': 'Mike and Fish',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/547/D',
			},
			{
				ID: '185',
				'Problem Name': 'Idempotent functions',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/542/C',
			},
			{
				ID: '186',
				'Problem Name': 'Data Center Drama',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/527/E',
			},
			{
				ID: '187',
				'Problem Name': 'Valera and Swaps',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/441/D',
			},
			{
				ID: '188',
				'Problem Name': 'Bug in Code',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/420/C',
			},
			{
				ID: '189',
				'Problem Name': "President's Path",
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/416/E',
			},
			{
				ID: '190',
				'Problem Name': 'Ksenia and Pawns',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/382/D',
			},
			{
				ID: '191',
				'Problem Name': 'Fools and Foolproof Roads',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/362/D',
			},
			{
				ID: '192',
				'Problem Name': 'Wrong Floyd',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/350/E',
			},
			{
				ID: '193',
				'Problem Name': 'Lovely Matrix',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/274/D',
			},
			{
				ID: '194',
				'Problem Name': 'Dima and Horses',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/272/E',
			},
			{
				ID: '195',
				'Problem Name': 'Black and White Tree',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/260/D',
			},
			{
				ID: '196',
				'Problem Name': 'Graph Cutting',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/405/E',
			},
			{
				ID: '197',
				'Problem Name': 'Envy',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/891/C',
			},
			{
				ID: '198',
				'Problem Name': 'Ant Man',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/704/B',
			},
			{
				ID: '199',
				'Problem Name': 'Okabe and City',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/821/D',
			},
			{
				ID: '200',
				'Problem Name': 'Ralph and Mushrooms',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/894/E',
			},
			{
				ID: '201',
				'Problem Name': 'Suggested Friends',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/245/G',
			},
			{
				ID: '202',
				'Problem Name': 'Flights',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/241/E',
			},
			{
				ID: '203',
				'Problem Name': 'T-decomposition',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/237/D',
			},
			{
				ID: '204',
				'Problem Name': 'Trails and Glades',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/209/C',
			},
			{
				ID: '205',
				'Problem Name': 'Opening Portals',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/196/E',
			},
			{
				ID: '206',
				'Problem Name': 'Clues',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/156/D',
			},
			{
				ID: '207',
				'Problem Name': 'Smile House',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/147/B',
			},
			{
				ID: '208',
				'Problem Name': 'Clearing Up',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/141/E',
			},
			{
				ID: '209',
				'Problem Name': 'Take-off Ramps',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/141/D',
			},
			{
				ID: '210',
				'Problem Name': 'Swaps',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/134/C',
			},
			{
				ID: '211',
				'Problem Name': 'MST Company',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/125/E',
			},
			{
				ID: '212',
				'Problem Name': 'Widget Library',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/89/B',
			},
			{
				ID: '213',
				'Problem Name': 'Guard Towers',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/85/E',
			},
			{
				ID: '214',
				'Problem Name': 'FreeDiv',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/73/D',
			},
			{
				ID: '215',
				'Problem Name': 'Quarrel',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/29/E',
			},
			{
				ID: '216',
				'Problem Name': 'Tickets',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/26/D',
			},
			{
				ID: '217',
				'Problem Name': 'Traveling Graph',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/21/D',
			},
			{
				ID: '218',
				'Problem Name': 'Interestring graph and Apples',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/9/E',
			},
			{
				ID: '220',
				'Problem Name': 'Magic Matrix',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/632/F',
			},
			{
				ID: '221',
				'Problem Name': 'Kingdom and its Cities',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/613/D',
			},
			{
				ID: '222',
				'Problem Name': 'CNF 2',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/571/C',
			},
			{
				ID: '223',
				'Problem Name': 'Playing on Graph',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/542/E',
			},
			{
				ID: '224',
				'Problem Name': 'Tourists',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/487/E',
			},
			{
				ID: '225',
				'Problem Name': 'Parcels',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/480/D',
			},
			{
				ID: '226',
				'Problem Name': 'Points and Segments',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/429/E',
			},
			{
				ID: '227',
				'Problem Name': 'Sereja and Tree',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/380/B',
			},
			{
				ID: '228',
				'Problem Name': 'Petya and Pipes',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/362/E',
			},
			{
				ID: '229',
				'Problem Name': 'Balance',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/317/C',
			},
			{
				ID: '230',
				'Problem Name': 'Dominoes',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/267/B',
			},
			{
				ID: '231',
				'Problem Name': 'BerDonalds',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/266/D',
			},
			{
				ID: '232',
				'Problem Name': 'Scheme',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/22/E',
			},
			{
				ID: '233',
				'Problem Name': 'Beads',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/8/E',
			},
			{
				ID: '234',
				'Problem Name': 'Tournament',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/878/C',
			},
			{
				ID: '235',
				'Problem Name': 'Vladik and Entertaining Flags',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/811/E',
			},
			{
				ID: '236',
				'Problem Name': 'Mother of Dragons',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '8',
				link: 'http://codeforces.com/problemset/problem/839/E',
			},
			{
				ID: '238',
				'Problem Name': 'Road Repairs',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '9',
				link: 'http://codeforces.com/problemset/problem/240/E',
			},
			{
				ID: '239',
				'Problem Name': 'Meeting Her',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '9',
				link: 'http://codeforces.com/problemset/problem/238/E',
			},
			{
				ID: '240',
				'Problem Name': 'Graph Game',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '9',
				link: 'http://codeforces.com/problemset/problem/235/D',
			},
			{
				ID: '241',
				'Problem Name': 'Metro Scheme',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '9',
				link: 'http://codeforces.com/problemset/problem/191/D',
			},
			{
				ID: '242',
				'Problem Name': 'Battlefield',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '9',
				link: 'http://codeforces.com/problemset/problem/182/A',
			},
			{
				ID: '243',
				'Problem Name': 'Deputies',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '9',
				link: 'http://codeforces.com/problemset/problem/173/D',
			},
			{
				ID: '244',
				'Problem Name': 'Garden',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '9',
				link: 'http://codeforces.com/problemset/problem/152/E',
			},
			{
				ID: '245',
				'Problem Name': 'Maze',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '9',
				link: 'http://codeforces.com/problemset/problem/123/E',
			},
			{
				ID: '246',
				'Problem Name': 'Winning Strategy',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '9',
				link: 'http://codeforces.com/problemset/problem/97/C',
			},
			{
				ID: '247',
				'Problem Name': "Grocer's Problem",
				'Online Judge': 'Codeforces',
				'Difficulty Level': '9',
				link: 'http://codeforces.com/problemset/problem/91/D',
			},
			{
				ID: '248',
				'Problem Name': 'Track',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '9',
				link: 'http://codeforces.com/problemset/problem/83/C',
			},
			{
				ID: '249',
				'Problem Name': 'Evacuation',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '9',
				link: 'http://codeforces.com/problemset/problem/78/E',
			},
			{
				ID: '250',
				'Problem Name': 'Wormhouse',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '9',
				link: 'http://codeforces.com/problemset/problem/62/D',
			},
			{
				ID: '251',
				'Problem Name': 'Caterpillar',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '9',
				link: 'http://codeforces.com/problemset/problem/51/F',
			},
			{
				ID: '252',
				'Problem Name': 'Pentagon',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '9',
				link: 'http://codeforces.com/problemset/problem/51/E',
			},
			{
				ID: '253',
				'Problem Name': 'Ivan the Fool VS Gorynych the Dragon',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '9',
				link: 'http://codeforces.com/problemset/problem/48/E',
			},
			{
				ID: '254',
				'Problem Name': 'Hercule Poirot Problem',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '9',
				link: 'http://codeforces.com/problemset/problem/46/F',
			},
			{
				ID: '255',
				'Problem Name': 'Trial for Chief',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '9',
				link: 'http://codeforces.com/problemset/problem/37/E',
			},
			{
				ID: '256',
				'Problem Name': 'Two Paths',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '9',
				link: 'http://codeforces.com/problemset/problem/36/E',
			},
			{
				ID: '257',
				'Problem Name': 'The Classic Problem',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '9',
				link: 'http://codeforces.com/problemset/problem/464/E',
			},
			{
				ID: '258',
				'Problem Name': 'Edge coloring of bipartite graph',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '9',
				link: 'http://codeforces.com/problemset/problem/600/F',
			},
			{
				ID: '259',
				'Problem Name': 'Wilbur and Strings',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '9',
				link: 'http://codeforces.com/problemset/problem/596/E',
			},
			{
				ID: '260',
				'Problem Name': 'Cycling City',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '9',
				link: 'http://codeforces.com/problemset/problem/521/E',
			},
			{
				ID: '261',
				'Problem Name': 'Big Problems for Organizers',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '9',
				link: 'http://codeforces.com/problemset/problem/418/D',
			},
			{
				ID: '262',
				'Problem Name': 'Game with Points',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '9',
				link: 'http://codeforces.com/problemset/problem/386/D',
			},
			{
				ID: '263',
				'Problem Name': 'Levko and Game',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '9',
				link: 'http://codeforces.com/problemset/problem/360/E',
			},
			{
				ID: '264',
				'Problem Name': 'Dima and Kicks',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '9',
				link: 'http://codeforces.com/problemset/problem/358/E',
			},
			{
				ID: '265',
				'Problem Name': 'Theft of Blueprints',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '9',
				link: 'http://codeforces.com/problemset/problem/332/D',
			},
			{
				ID: '266',
				'Problem Name': 'Pairs',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '9',
				link: 'http://codeforces.com/problemset/problem/81/E',
			},
			{
				ID: '267',
				'Problem Name': "Travelling Through the Snow Queen's Kingdom",
				'Online Judge': 'Codeforces',
				'Difficulty Level': '9',
				link: 'http://codeforces.com/problemset/problem/685/E',
			},
			{
				ID: '268',
				'Problem Name': 'Mister B and Flight to the Moon',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '9',
				link: 'http://codeforces.com/problemset/problem/819/E',
			},
			{
				ID: '269',
				'Problem Name': 'Sagheer and Kindergarten',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '9',
				link: 'http://codeforces.com/problemset/problem/812/D',
			},
			{
				ID: '270',
				'Problem Name': 'Mike and code of a permutation',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '9',
				link: 'http://codeforces.com/problemset/problem/798/E',
			},
			{
				ID: '271',
				'Problem Name': 'DFS',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '9',
				link: 'http://codeforces.com/problemset/problem/1044/F',
			},
			{
				ID: '272',
				'Problem Name': 'Doe Graphs',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '10',
				link: 'http://codeforces.com/problemset/problem/232/C',
			},
			{
				ID: '273',
				'Problem Name': 'Planar Graph',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '10',
				link: 'http://codeforces.com/problemset/problem/223/E',
			},
			{
				ID: '274',
				'Problem Name': 'Spider',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '10',
				link: 'http://codeforces.com/problemset/problem/223/D',
			},
			{
				ID: '275',
				'Problem Name': 'Privatization',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '10',
				link: 'http://codeforces.com/problemset/problem/212/A',
			},
			{
				ID: '276',
				'Problem Name': 'Gnomes of Might and Magic',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '10',
				link: 'http://codeforces.com/problemset/problem/175/F',
			},
			{
				ID: '277',
				'Problem Name': 'Leaders',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '10',
				link: 'http://codeforces.com/problemset/problem/97/E',
			},
			{
				ID: '278',
				'Problem Name': 'Road Problem',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '10',
				link: 'http://codeforces.com/problemset/problem/45/H',
			},
			{
				ID: '279',
				'Problem Name': 'Baldman and the military',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '10',
				link: 'http://codeforces.com/problemset/problem/42/E',
			},
			{
				ID: '280',
				'Problem Name': 'Bear and Chemistry',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '10',
				link: 'http://codeforces.com/problemset/problem/639/F',
			},
			{
				ID: '281',
				'Problem Name': 'Island Puzzle',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '10',
				link: 'http://codeforces.com/problemset/problem/627/F',
			},
			{
				ID: '282',
				'Problem Name': 'Chain Letter',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '10',
				link: 'http://codeforces.com/problemset/problem/345/D',
			},
			{
				ID: '283',
				'Problem Name': 'Deja Vu',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '10',
				link: 'http://codeforces.com/problemset/problem/331/E1',
			},
			{
				ID: '284',
				'Problem Name': 'Escaping on Beaveractor',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '10',
				link: 'http://codeforces.com/problemset/problem/331/D2',
			},
			{
				ID: '285',
				'Problem Name': 'Greedy Petya',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '10',
				link: 'http://codeforces.com/problemset/problem/290/F',
			},
			{
				ID: '286',
				'Problem Name': 'BerPaint',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '10',
				link: 'http://codeforces.com/problemset/problem/44/F',
			},
			{
				ID: '288',
				'Problem Name': 'Shake It!',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '10',
				link: 'http://codeforces.com/problemset/problem/848/D',
			},
			{
				ID: '289',
				'Problem Name': 'ALT',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '10',
				link: 'http://codeforces.com/problemset/problem/786/E',
			},
			{
				ID: '290',
				'Problem Name': 'Restore the Tree',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '10',
				link: 'http://codeforces.com/problemset/problem/871/E',
			},
			{
				ID: '291',
				'Problem Name': 'The Overdosing Ubiquity',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '10',
				link: 'http://codeforces.com/problemset/problem/869/D',
			},
		],
	},
	{
		id: 6,
		name: 'digit dp',
		problems: [
			{
				ID: '4',
				'Problem Name': 'Magic Numbers',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '6',
				link: 'http://codeforces.com/problemset/problem/628/D',
			},
			{
				ID: '5',
				'Problem Name': "Salazar Slytherin's Locket",
				'Online Judge': 'Codeforces',
				'Difficulty Level': '7',
				link: 'http://codeforces.com/problemset/problem/855/E',
			},
			{
				ID: '6',
				'Problem Name': 'Igor and Interesting Numbers',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '9',
				link: 'http://codeforces.com/problemset/problem/747/F',
			},
		],
	},
	{
		id: 7,
		name: 'bfs',
		problems: [
			{
				ID: '33',
				'Problem Name': 'Valid BFS?',
				'Online Judge': 'Codeforces',
				'Difficulty Level': '3',
				link: 'http://codeforces.com/problemset/problem/1037/D',
			},
		],
	},
];
